### ISSUE TITLE
Gap property for Flexbox is not supported before iOS 14.5

### ISSUE THREAD

**Issue by lievenjanssen** [philmtd/css-fx-layout#10]
Potential workaround for Safari: https://ppuzio.medium.com/flexbox-gap-workaround-for-safari-on-ios-14-13-and-lower-ffcae589eb69

Once an implementation for a fix is agreed upon I'm willing to do the fix and open a PR.

**Comment by lievenjanssen** [comment]
We have some users that still use iOS < 14.5 but I agree that it's better to avoid adding a compatibility layer in this codebase.

We will be looking into using PostCSS with the flex-gap-polyfill plugin (https://github.com/gavinmcfarland/flex-gap-polyfill) to add support for iOS < 14.5.

**Comment by philmtd** [comment]
Yes that sounds like a good idea! I'm closing this issue, then. Thank you!
