### ISSUE TITLE
Gap doesn't work with bigger than 16px

### ISSUE THREAD

**Issue by Wlada** [philmtd/css-fx-layout#23]
Very interesting issue, but gap it's not working if you enter more than 16 pixels

**Comment by Wlada** [comment]
MY bad, sorry. I had to define it here to 50
@include fx.gap-attribute-selectors(1, 50, 1, px em, $includeResponsiveApi);

**Comment by philmtd** [comment]
Glad it was a simple solution. Thanks for closing the issue!
