### ISSUE TITLE
sm breakpoint uses wrong size

### ISSUE THREAD

**Issue by dungvq23** [philmtd/css-fx-layout#24]
i saw the documentation of breakpoints is declared: $sm: 969px. I reckon it should be 959px.

**Comment by philmtd** [comment]
Hello! Thank you for this bug report. Indeed, in some parts of the documentation and in the code $sm is declared as 969px but it should be 959px. I will fix this in the next release.

**Comment by philmtd** [comment]
I just released the fix in 3.0.3.
