### ISSUE TITLE
Errors after converting sveltekit to use .scss instead of .css

### ISSUE THREAD

**Issue by st-clair-clarke** [philmtd/css-fx-layout#37]
After converting to my app.css to app.scss with appropriate changes, I am now getting a lot of generated errors about deprecations. Some are shown in the screenshot

![image](https://github.com/user-attachments/assets/3e4c52fd-fd11-4be3-b352-7df23bee4cef)

Any possibility of correcting them?

Cheers

**Comment by philmtd** [comment]
Hi, thanks for letting me know. Apparently, starting with sass 3.0.0 `@import` is deprecated. For now you can use it like this. I'll also try to make a new release that fixes this, soon.

**Comment by st-clair-clarke** [comment]
Great!

**Comment by philmtd** [comment]
I just released an updated version as 3.0.5 which resolves the deprecation warnings. Let me know if you have further questions.

**Comment by st-clair-clarke** [comment]
It did. Thanks.
